// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CTeDQHfFmqWwinuFlgd8omjyFhvYcpQ',
    appId: '1:709010225952:web:1a853af670cf746da13545',
    messagingSenderId: '709010225952',
    projectId: 'recipe-book-aee4c',
    authDomain: 'recipe-book-aee4c.firebaseapp.com',
    storageBucket: 'recipe-book-aee4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtp8Xogztr8oZVMDuzXz6BFYBUvTodhyw',
    appId: '1:709010225952:android:11ad1c127a696d1aa13545',
    messagingSenderId: '709010225952',
    projectId: 'recipe-book-aee4c',
    storageBucket: 'recipe-book-aee4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjiv43qnuobyp6-YgsHXm2U7gpYAK5xqE',
    appId: '1:709010225952:ios:676b3d6296376c4ba13545',
    messagingSenderId: '709010225952',
    projectId: 'recipe-book-aee4c',
    storageBucket: 'recipe-book-aee4c.firebasestorage.app',
    iosBundleId: 'com.addiscodr.recipeBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjiv43qnuobyp6-YgsHXm2U7gpYAK5xqE',
    appId: '1:709010225952:ios:676b3d6296376c4ba13545',
    messagingSenderId: '709010225952',
    projectId: 'recipe-book-aee4c',
    storageBucket: 'recipe-book-aee4c.firebasestorage.app',
    iosBundleId: 'com.addiscodr.recipeBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9CTeDQHfFmqWwinuFlgd8omjyFhvYcpQ',
    appId: '1:709010225952:web:f9edfaaefe5f70c5a13545',
    messagingSenderId: '709010225952',
    projectId: 'recipe-book-aee4c',
    authDomain: 'recipe-book-aee4c.firebaseapp.com',
    storageBucket: 'recipe-book-aee4c.firebasestorage.app',
  );
}
